// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// StudyTime is the predicate function for studytime builders.
type StudyTime func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
