// Code generated by ent, DO NOT EDIT.

package studytime

import (
	"next_go_blog/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldTitle, v))
}

// Hour applies equality check predicate on the "hour" field. It's identical to HourEQ.
func Hour(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldHour, v))
}

// Minite applies equality check predicate on the "minite" field. It's identical to MiniteEQ.
func Minite(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldMinite, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNotIn(FieldUserID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldContainsFold(FieldTitle, v))
}

// HourEQ applies the EQ predicate on the "hour" field.
func HourEQ(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldHour, v))
}

// HourNEQ applies the NEQ predicate on the "hour" field.
func HourNEQ(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNEQ(FieldHour, v))
}

// HourIn applies the In predicate on the "hour" field.
func HourIn(vs ...int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldIn(FieldHour, vs...))
}

// HourNotIn applies the NotIn predicate on the "hour" field.
func HourNotIn(vs ...int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNotIn(FieldHour, vs...))
}

// HourGT applies the GT predicate on the "hour" field.
func HourGT(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGT(FieldHour, v))
}

// HourGTE applies the GTE predicate on the "hour" field.
func HourGTE(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGTE(FieldHour, v))
}

// HourLT applies the LT predicate on the "hour" field.
func HourLT(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLT(FieldHour, v))
}

// HourLTE applies the LTE predicate on the "hour" field.
func HourLTE(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLTE(FieldHour, v))
}

// MiniteEQ applies the EQ predicate on the "minite" field.
func MiniteEQ(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldMinite, v))
}

// MiniteNEQ applies the NEQ predicate on the "minite" field.
func MiniteNEQ(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNEQ(FieldMinite, v))
}

// MiniteIn applies the In predicate on the "minite" field.
func MiniteIn(vs ...int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldIn(FieldMinite, vs...))
}

// MiniteNotIn applies the NotIn predicate on the "minite" field.
func MiniteNotIn(vs ...int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNotIn(FieldMinite, vs...))
}

// MiniteGT applies the GT predicate on the "minite" field.
func MiniteGT(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGT(FieldMinite, v))
}

// MiniteGTE applies the GTE predicate on the "minite" field.
func MiniteGTE(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGTE(FieldMinite, v))
}

// MiniteLT applies the LT predicate on the "minite" field.
func MiniteLT(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLT(FieldMinite, v))
}

// MiniteLTE applies the LTE predicate on the "minite" field.
func MiniteLTE(v int) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLTE(FieldMinite, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StudyTime {
	return predicate.StudyTime(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.StudyTime {
	return predicate.StudyTime(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.StudyTime {
	return predicate.StudyTime(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StudyTime) predicate.StudyTime {
	return predicate.StudyTime(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StudyTime) predicate.StudyTime {
	return predicate.StudyTime(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StudyTime) predicate.StudyTime {
	return predicate.StudyTime(sql.NotPredicates(p))
}
