// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"next_go_blog/ent/predicate"
	"next_go_blog/ent/studytime"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudyTimeDelete is the builder for deleting a StudyTime entity.
type StudyTimeDelete struct {
	config
	hooks    []Hook
	mutation *StudyTimeMutation
}

// Where appends a list predicates to the StudyTimeDelete builder.
func (std *StudyTimeDelete) Where(ps ...predicate.StudyTime) *StudyTimeDelete {
	std.mutation.Where(ps...)
	return std
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (std *StudyTimeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, std.sqlExec, std.mutation, std.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (std *StudyTimeDelete) ExecX(ctx context.Context) int {
	n, err := std.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (std *StudyTimeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(studytime.Table, sqlgraph.NewFieldSpec(studytime.FieldID, field.TypeInt))
	if ps := std.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, std.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	std.mutation.done = true
	return affected, err
}

// StudyTimeDeleteOne is the builder for deleting a single StudyTime entity.
type StudyTimeDeleteOne struct {
	std *StudyTimeDelete
}

// Where appends a list predicates to the StudyTimeDelete builder.
func (stdo *StudyTimeDeleteOne) Where(ps ...predicate.StudyTime) *StudyTimeDeleteOne {
	stdo.std.mutation.Where(ps...)
	return stdo
}

// Exec executes the deletion query.
func (stdo *StudyTimeDeleteOne) Exec(ctx context.Context) error {
	n, err := stdo.std.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{studytime.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (stdo *StudyTimeDeleteOne) ExecX(ctx context.Context) {
	if err := stdo.Exec(ctx); err != nil {
		panic(err)
	}
}
