// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"next_go_blog/ent/predicate"
	"next_go_blog/ent/studytime"
	"next_go_blog/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudyTimeQuery is the builder for querying StudyTime entities.
type StudyTimeQuery struct {
	config
	ctx        *QueryContext
	order      []studytime.OrderOption
	inters     []Interceptor
	predicates []predicate.StudyTime
	withUsers  *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StudyTimeQuery builder.
func (stq *StudyTimeQuery) Where(ps ...predicate.StudyTime) *StudyTimeQuery {
	stq.predicates = append(stq.predicates, ps...)
	return stq
}

// Limit the number of records to be returned by this query.
func (stq *StudyTimeQuery) Limit(limit int) *StudyTimeQuery {
	stq.ctx.Limit = &limit
	return stq
}

// Offset to start from.
func (stq *StudyTimeQuery) Offset(offset int) *StudyTimeQuery {
	stq.ctx.Offset = &offset
	return stq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (stq *StudyTimeQuery) Unique(unique bool) *StudyTimeQuery {
	stq.ctx.Unique = &unique
	return stq
}

// Order specifies how the records should be ordered.
func (stq *StudyTimeQuery) Order(o ...studytime.OrderOption) *StudyTimeQuery {
	stq.order = append(stq.order, o...)
	return stq
}

// QueryUsers chains the current query on the "users" edge.
func (stq *StudyTimeQuery) QueryUsers() *UserQuery {
	query := (&UserClient{config: stq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := stq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := stq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(studytime.Table, studytime.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, studytime.UsersTable, studytime.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(stq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StudyTime entity from the query.
// Returns a *NotFoundError when no StudyTime was found.
func (stq *StudyTimeQuery) First(ctx context.Context) (*StudyTime, error) {
	nodes, err := stq.Limit(1).All(setContextOp(ctx, stq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{studytime.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (stq *StudyTimeQuery) FirstX(ctx context.Context) *StudyTime {
	node, err := stq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StudyTime ID from the query.
// Returns a *NotFoundError when no StudyTime ID was found.
func (stq *StudyTimeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = stq.Limit(1).IDs(setContextOp(ctx, stq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{studytime.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (stq *StudyTimeQuery) FirstIDX(ctx context.Context) int {
	id, err := stq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StudyTime entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StudyTime entity is found.
// Returns a *NotFoundError when no StudyTime entities are found.
func (stq *StudyTimeQuery) Only(ctx context.Context) (*StudyTime, error) {
	nodes, err := stq.Limit(2).All(setContextOp(ctx, stq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{studytime.Label}
	default:
		return nil, &NotSingularError{studytime.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (stq *StudyTimeQuery) OnlyX(ctx context.Context) *StudyTime {
	node, err := stq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StudyTime ID in the query.
// Returns a *NotSingularError when more than one StudyTime ID is found.
// Returns a *NotFoundError when no entities are found.
func (stq *StudyTimeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = stq.Limit(2).IDs(setContextOp(ctx, stq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{studytime.Label}
	default:
		err = &NotSingularError{studytime.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (stq *StudyTimeQuery) OnlyIDX(ctx context.Context) int {
	id, err := stq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StudyTimes.
func (stq *StudyTimeQuery) All(ctx context.Context) ([]*StudyTime, error) {
	ctx = setContextOp(ctx, stq.ctx, "All")
	if err := stq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StudyTime, *StudyTimeQuery]()
	return withInterceptors[[]*StudyTime](ctx, stq, qr, stq.inters)
}

// AllX is like All, but panics if an error occurs.
func (stq *StudyTimeQuery) AllX(ctx context.Context) []*StudyTime {
	nodes, err := stq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StudyTime IDs.
func (stq *StudyTimeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if stq.ctx.Unique == nil && stq.path != nil {
		stq.Unique(true)
	}
	ctx = setContextOp(ctx, stq.ctx, "IDs")
	if err = stq.Select(studytime.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (stq *StudyTimeQuery) IDsX(ctx context.Context) []int {
	ids, err := stq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (stq *StudyTimeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, stq.ctx, "Count")
	if err := stq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, stq, querierCount[*StudyTimeQuery](), stq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (stq *StudyTimeQuery) CountX(ctx context.Context) int {
	count, err := stq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (stq *StudyTimeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, stq.ctx, "Exist")
	switch _, err := stq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (stq *StudyTimeQuery) ExistX(ctx context.Context) bool {
	exist, err := stq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StudyTimeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (stq *StudyTimeQuery) Clone() *StudyTimeQuery {
	if stq == nil {
		return nil
	}
	return &StudyTimeQuery{
		config:     stq.config,
		ctx:        stq.ctx.Clone(),
		order:      append([]studytime.OrderOption{}, stq.order...),
		inters:     append([]Interceptor{}, stq.inters...),
		predicates: append([]predicate.StudyTime{}, stq.predicates...),
		withUsers:  stq.withUsers.Clone(),
		// clone intermediate query.
		sql:  stq.sql.Clone(),
		path: stq.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (stq *StudyTimeQuery) WithUsers(opts ...func(*UserQuery)) *StudyTimeQuery {
	query := (&UserClient{config: stq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	stq.withUsers = query
	return stq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StudyTime.Query().
//		GroupBy(studytime.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (stq *StudyTimeQuery) GroupBy(field string, fields ...string) *StudyTimeGroupBy {
	stq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StudyTimeGroupBy{build: stq}
	grbuild.flds = &stq.ctx.Fields
	grbuild.label = studytime.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.StudyTime.Query().
//		Select(studytime.FieldUserID).
//		Scan(ctx, &v)
func (stq *StudyTimeQuery) Select(fields ...string) *StudyTimeSelect {
	stq.ctx.Fields = append(stq.ctx.Fields, fields...)
	sbuild := &StudyTimeSelect{StudyTimeQuery: stq}
	sbuild.label = studytime.Label
	sbuild.flds, sbuild.scan = &stq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StudyTimeSelect configured with the given aggregations.
func (stq *StudyTimeQuery) Aggregate(fns ...AggregateFunc) *StudyTimeSelect {
	return stq.Select().Aggregate(fns...)
}

func (stq *StudyTimeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range stq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, stq); err != nil {
				return err
			}
		}
	}
	for _, f := range stq.ctx.Fields {
		if !studytime.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if stq.path != nil {
		prev, err := stq.path(ctx)
		if err != nil {
			return err
		}
		stq.sql = prev
	}
	return nil
}

func (stq *StudyTimeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StudyTime, error) {
	var (
		nodes       = []*StudyTime{}
		_spec       = stq.querySpec()
		loadedTypes = [1]bool{
			stq.withUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StudyTime).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StudyTime{config: stq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, stq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := stq.withUsers; query != nil {
		if err := stq.loadUsers(ctx, query, nodes, nil,
			func(n *StudyTime, e *User) { n.Edges.Users = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (stq *StudyTimeQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*StudyTime, init func(*StudyTime), assign func(*StudyTime, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*StudyTime)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (stq *StudyTimeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := stq.querySpec()
	_spec.Node.Columns = stq.ctx.Fields
	if len(stq.ctx.Fields) > 0 {
		_spec.Unique = stq.ctx.Unique != nil && *stq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, stq.driver, _spec)
}

func (stq *StudyTimeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(studytime.Table, studytime.Columns, sqlgraph.NewFieldSpec(studytime.FieldID, field.TypeInt))
	_spec.From = stq.sql
	if unique := stq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if stq.path != nil {
		_spec.Unique = true
	}
	if fields := stq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, studytime.FieldID)
		for i := range fields {
			if fields[i] != studytime.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if stq.withUsers != nil {
			_spec.Node.AddColumnOnce(studytime.FieldUserID)
		}
	}
	if ps := stq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := stq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := stq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := stq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (stq *StudyTimeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(stq.driver.Dialect())
	t1 := builder.Table(studytime.Table)
	columns := stq.ctx.Fields
	if len(columns) == 0 {
		columns = studytime.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if stq.sql != nil {
		selector = stq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if stq.ctx.Unique != nil && *stq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range stq.predicates {
		p(selector)
	}
	for _, p := range stq.order {
		p(selector)
	}
	if offset := stq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := stq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StudyTimeGroupBy is the group-by builder for StudyTime entities.
type StudyTimeGroupBy struct {
	selector
	build *StudyTimeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (stgb *StudyTimeGroupBy) Aggregate(fns ...AggregateFunc) *StudyTimeGroupBy {
	stgb.fns = append(stgb.fns, fns...)
	return stgb
}

// Scan applies the selector query and scans the result into the given value.
func (stgb *StudyTimeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, stgb.build.ctx, "GroupBy")
	if err := stgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StudyTimeQuery, *StudyTimeGroupBy](ctx, stgb.build, stgb, stgb.build.inters, v)
}

func (stgb *StudyTimeGroupBy) sqlScan(ctx context.Context, root *StudyTimeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(stgb.fns))
	for _, fn := range stgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*stgb.flds)+len(stgb.fns))
		for _, f := range *stgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*stgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := stgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StudyTimeSelect is the builder for selecting fields of StudyTime entities.
type StudyTimeSelect struct {
	*StudyTimeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sts *StudyTimeSelect) Aggregate(fns ...AggregateFunc) *StudyTimeSelect {
	sts.fns = append(sts.fns, fns...)
	return sts
}

// Scan applies the selector query and scans the result into the given value.
func (sts *StudyTimeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sts.ctx, "Select")
	if err := sts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StudyTimeQuery, *StudyTimeSelect](ctx, sts.StudyTimeQuery, sts, sts.inters, v)
}

func (sts *StudyTimeSelect) sqlScan(ctx context.Context, root *StudyTimeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sts.fns))
	for _, fn := range sts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
